  version: '3'
  services:
    mongo:
      image: mongo
      restart: always
      ports:
        - 27017:27017
    redis_db:
      image: redis
      restart: always
      ports:
        - 6379:6379
      container_name: "redis_db"
    backend:
      build:
        dockerfile: Dockerfile
        context: ./backend
      privileged: true
      user: root
      ports:
       - 3001:3001
      container_name: backend
      environment:
        - REDIS_HOST=redis_db
      links:
        - "redis_db"
    