
###

GET http://localhost:3001/post

###
GET http://localhost:3001/post?sender=liron
###
GET http://localhost:3001/post/622f09afd5fa3a81dc48fa5b
###

POST http://localhost:3001/post
Content-Type: application/json

{
    "message" : "this is my first message",
    "sender" : "Ohad"
}

###
POST http://localhost:3001/post/updateSender/6263fba45094e7f66ca56f88
Content-Type: application/json

{
    "update" :"Ohad"
}


###
GET http://localhost:3001/post/getPostBySender
Content-Type: application/json

{
    "sender" :"Ohad"
}

###
POST http://localhost:3001/post/updateMessage/6263fba45094e7f66ca56f88
Content-Type: application/json

{
    "update" :"new message"
}

###

POST http://localhost:3001/auth/register
Content-Type: application/json

{
    "email" : "test@test.com",
    "password" : "2282222"
}
###

POST http://localhost:3001/auth/login
Content-Type: application/json

{
    "email" : "t11@a.com",
    "password" : "2282222"
}