version: 2.1
jobs:
  build:
    docker:
      - image: node:alpine

    steps:
      - checkout
      - run:
          name: Installing dependencies
          command: |
            ls -al
            echo " files "
            cd backend/
            npm install
            npm run test